spring.application.name=api-usuarios

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5435/bdapiusuarios
spring.datasource.username=apiusuarios
spring.datasource.password=coti2026
spring.datasource..driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cors.enabled=http://localhost:4200

jwt.secret=73fe9e8d-1165-4178-b702-845dc8dfedb5
jwt.expiration=3600000